# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto3/models.proto3

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto3/models.proto3',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14proto3/models.proto3\"g\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x1f\n\x08\x63\x61tegory\x18\x02 \x01(\x0e\x32\r.ItemCategory\x12\x10\n\x08tradable\x18\x03 \x01(\x08\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x12\n\nuniqueName\x18\x06 \x01(\t*\xb0\x02\n\x0cItemCategory\x12\x0b\n\x07\x41rcanes\x10\x00\x12\x0b\n\x07\x41rchGun\x10\x01\x12\r\n\tArchMelee\x10\x02\x12\x0c\n\x08\x41rchwing\x10\x03\x12\t\n\x05\x45nemy\x10\x04\x12\x08\n\x04\x46ish\x10\x05\x12\x08\n\x04Gear\x10\x06\x12\n\n\x06Glyphs\x10\x07\x12\t\n\x05Melee\x10\x08\x12\x08\n\x04Misc\x10\t\x12\x08\n\x04Mods\x10\n\x12\x08\n\x04Node\x10\x0b\x12\x08\n\x04Pets\x10\x0c\x12\x0b\n\x07Primary\x10\r\x12\n\n\x06Quests\x10\x0e\x12\n\n\x06Relics\x10\x0f\x12\r\n\tResources\x10\x10\x12\r\n\tSecondary\x10\x11\x12\r\n\tSentinels\x10\x12\x12\x13\n\x0fSentinelWeapons\x10\x13\x12\n\n\x06Sigils\x10\x14\x12\t\n\x05Skins\x10\x15\x12\r\n\tWarframes\x10\x16\x62\x06proto3')
)

_ITEMCATEGORY = _descriptor.EnumDescriptor(
  name='ItemCategory',
  full_name='ItemCategory',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Arcanes', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ArchGun', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ArchMelee', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Archwing', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Enemy', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Fish', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Gear', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Glyphs', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Melee', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Misc', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Mods', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Node', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Pets', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Primary', index=13, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Quests', index=14, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Relics', index=15, number=15,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Resources', index=16, number=16,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Secondary', index=17, number=17,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Sentinels', index=18, number=18,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SentinelWeapons', index=19, number=19,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Sigils', index=20, number=20,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Skins', index=21, number=21,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Warframes', index=22, number=22,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=130,
  serialized_end=434,
)
_sym_db.RegisterEnumDescriptor(_ITEMCATEGORY)

ItemCategory = enum_type_wrapper.EnumTypeWrapper(_ITEMCATEGORY)
Arcanes = 0
ArchGun = 1
ArchMelee = 2
Archwing = 3
Enemy = 4
Fish = 5
Gear = 6
Glyphs = 7
Melee = 8
Misc = 9
Mods = 10
Node = 11
Pets = 12
Primary = 13
Quests = 14
Relics = 15
Resources = 16
Secondary = 17
Sentinels = 18
SentinelWeapons = 19
Sigils = 20
Skins = 21
Warframes = 22



_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Item.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='category', full_name='Item.category', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tradable', full_name='Item.tradable', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='Item.type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uniqueName', full_name='Item.uniqueName', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=127,
)

_ITEM.fields_by_name['category'].enum_type = _ITEMCATEGORY
DESCRIPTOR.message_types_by_name['Item'] = _ITEM
DESCRIPTOR.enum_types_by_name['ItemCategory'] = _ITEMCATEGORY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(
  DESCRIPTOR = _ITEM,
  __module__ = 'proto3.models.proto3_pb2'
  # @@protoc_insertion_point(class_scope:Item)
  ))
_sym_db.RegisterMessage(Item)


# @@protoc_insertion_point(module_scope)
